export const ValidPassword = 'Admin@123$'
export const ValidUserid = 'prabhakaran+357@bridgeup.com'
export const HomePageUrl ='https://bridgeup.com/'
export const Authid ='auth.bridgeup.com'
export const hasuraid ='api.bridgeup.com'
